var names = ["John", "Paul", "George", "Ringo", "Stuart", "Brian", "Ron", "Charlie", "Bill", "Steve", "Mike", "Jim", "Peter", "Alan", "Bob", "Joe", "Tom"]

var items=[
        {
            nazwa : "Półka",
            opis : "Mała półka",
            lvl : 1,
            typ : "polka",
            png : "polka-1",
            staly: true,
            sellValue : 10,
            buyValue : 100,
            decx: 0,
            decy: -480,
            others : {},
        },{
            nazwa : "Kasa fiskalna",
            opis : "Kasa fiskalna",
            lvl : 1,
            typ : "kasa",
            png : "slupek",
            staly: true,
            sellValue : 10,
            buyValue : 100,
            decx: 0,
            decy: -10,
            others : {},
        },{
            nazwa : "Dywan",
            opis : "Ładny dywan, ludzie chętniej po nim chodzą",
            lvl : 1,
            typ : "dywan",
            png : "dywan_red",
            staly: false,
            sellValue : 5,
            buyValue : 50,
            decx: 0,
            decy:0,
            others : {},
        },{
            nazwa : "Drzwi",
            opis : "Pozwala klientom wejś do sklepu",
            lvl : 1,
            typ : "drzwi",
            png : "dzrzwi",
            staly: false,
            sellValue : 1000,
            buyValue : 1000,
            decx: 0,
            decy:0,
            others : {},
        },{
            nazwa : "Kwiatek",
            opis : "Ładny kwiatek w doniczce",
            lvl : 1,
            typ : "kwiatek",
            png : "",
            staly: true,
            sellValue : 0,
            buyValue : 50,
            decx: 0,
            decy:0,
            others : {},
        },{
            nazwa : "Plakat",
            opis : "Plakat, czy jak to sie tam nazywa?",
            lvl : 1,
            typ : "plakat",
            png : "",
            staly: false,
            sellValue : 0,
            buyValue : 50,
            decx: 0,
            decy:0,
            others : {},
        }
    
]